# Generated by Django 4.0.4 on 2022-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itnext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
    ]
