# Generated by Django 4.0.4 on 2022-05-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itnext', '0003_brands'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brands',
        ),
    ]
